[package]
name = "function-like-compose-with-different-token-exercise-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.39", features = ["extra-traits"]}
proc-macro2 = "1.0.69"

[lib]
proc-macro = true